DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(250),
  email VARCHAR(254),
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_user_email UNIQUE (email)
);

DROP TABLE IF EXISTS categories CASCADE;
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50),
  CONSTRAINT pk_category PRIMARY KEY (id)
);

DROP TABLE IF EXISTS locations CASCADE;
CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lat FLOAT,
  lon FLOAT,
  CONSTRAINT pk_location PRIMARY KEY (id)
);

DROP TABLE IF EXISTS events CASCADE;
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation VARCHAR(2000),
  category_id BIGINT REFERENCES categories(id),
  confirmed_requests INT,
  created_on TIMESTAMP,
  description VARCHAR(7000),
  event_date TIMESTAMP,
  user_id BIGINT REFERENCES users(id),
  location BIGINT REFERENCES locations(id),
  paid BOOL,
  participant_limit INT,
  published_on TIMESTAMP,
  request_moderation BOOL,
  state VARCHAR,
  title VARCHAR(120),
  comment_state VARCHAR,
  CONSTRAINT pk_event PRIMARY KEY (id)
  );

  DROP TABLE IF EXISTS compilations CASCADE;
  CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    events BIGINT REFERENCES events(id),
    pinned BOOL,
    title VARCHAR(50),
    CONSTRAINT pk_compilation PRIMARY KEY (id)
  );

  DROP TABLE IF EXISTS compilations_event CASCADE;
  CREATE TABLE IF NOT EXISTS compilations_event (
      event_id bigint not null,
      compilation_id bigint not null,
      CONSTRAINT pk_compilation_event PRIMARY KEY (event_id, compilation_id)
  );

  DROP TABLE IF EXISTS requests CASCADE;
  CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created timestamp,
    event_id BIGINT REFERENCES events(id),
    user_id BIGINT REFERENCES users(id),
    status VARCHAR,
    CONSTRAINT pk_request PRIMARY KEY (id)
  );

  DROP TABLE IF EXISTS comments CASCADE;
  CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment VARCHAR(1000),
    created TIMESTAMP,
    edited TIMESTAMP,
    event_id BIGINT REFERENCES events(id),
    user_id BIGINT REFERENCES users(id),
    comment_state VARCHAR,
    CONSTRAINT pk_comment PRIMARY KEY(id)
  );