DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR,
  email VARCHAR ,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_user_email UNIQUE (email)
);

DROP TABLE IF EXISTS categories CASCADE;
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR,
  CONSTRAINT pk_category PRIMARY KEY (id)
);

DROP TABLE IF EXISTS locations CASCADE;
CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lat FLOAT,
  lon FLOAT,
  CONSTRAINT pk_location PRIMARY KEY (id)
);

DROP TABLE IF EXISTS events CASCADE;
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation VARCHAR,
  category_id BIGINT REFERENCES categories(id),
  confirmed_requests INT,
  created_on TIMESTAMP,
  description VARCHAR,
  event_date TIMESTAMP,
  user_id BIGINT REFERENCES users(id),
  location BIGINT REFERENCES locations(id),
  paid BOOL,
  participant_limit INT,
  published_on TIMESTAMP,
  request_moderation BOOL,
  state VARCHAR,
  title VARCHAR,
  views INT,
  CONSTRAINT pk_event PRIMARY KEY (id)
  );

  DROP TABLE IF EXISTS compilations CASCADE;
  CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    events BIGINT REFERENCES events(id),
    pinned BOOL,
    title VARCHAR,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
  );

  DROP TABLE IF EXISTS compilations_event CASCADE;
  CREATE TABLE IF NOT EXISTS compilations_event (
      event_id bigint not null,
      compilation_id bigint not null
  );

  DROP TABLE IF EXISTS requests CASCADE;
  CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created timestamp,
    event_id BIGINT REFERENCES events(id),
    user_id BIGINT REFERENCES users(id),
    status VARCHAR,
    CONSTRAINT pk_request PRIMARY KEY (id)
  );