version: '3.8'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: main-service
    image: ewm-server-image
    container_name: main-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/

  ewm-db:
    container_name: ewm-db
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot